// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/meetings/new": {
    params: {};
  };
  "/meetings/:id": {
    params: {
      "id": string;
    };
  };
  "/meetings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/meetings/new" | "/meetings/:id" | "/meetings";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/meetings.new.tsx": {
    id: "routes/meetings.new";
    page: "/meetings/new";
  };
  "routes/meetings.$id.tsx": {
    id: "routes/meetings.$id";
    page: "/meetings/:id";
  };
  "routes/meetings._index.tsx": {
    id: "routes/meetings._index";
    page: "/meetings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/meetings.new": typeof import("./app/routes/meetings.new.tsx");
  "routes/meetings.$id": typeof import("./app/routes/meetings.$id.tsx");
  "routes/meetings._index": typeof import("./app/routes/meetings._index.tsx");
};